
server:
  port: 8080


spring:
  application:
    name: LubberDuck

  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbDuck?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: userDuck
    password: 1234

  # security 설정
  security:
    #    user:
    #      name: user
    #      password: 1234
    # oauth2 client
    oauth2:
      client:
        registration:
          naver:
            client-id: WSZcJ1CC0pKHgPqI9Vw1
            client-secret: Hbwn1sIKp5
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

kakaopay:
  admin-key: 25e44abe470ff7af73dfb19a783ae860
  cid: TC0ONETIME

cohere:
  api:
    key: 8ZyktgQ2vDfKh1miXacNNK5CoSvM5vvBuqQRDEg7


app:
  # pagination
  pagination:
    write_pages: 5
    page_rows: 4

  # OAuth2
  oauth2:

    password: 1234   # oauth2 인증한 회원에 대한 전용 패스워드, 보안주의!

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: 0da1e13be817903328983167f317f64d    # REST Api 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token  # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청 URI
