server:
  port: 80


spring:
  application:
    name: LubberDuck

  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security 설정
  security:
    #    user:
    #      name: user
    #      password: 1234
    # oauth2 client
    oauth2:
      client:
        registration:
          naver:
            client-id: ${rds.naverid}
            client-secret: ${rds.naversecret}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.naverredirecturl}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

kakaopay:
  admin-key: ${rds.kakaokey}
  cid: ${rds.kakaocid}

cohere:
  api:
    key: ${rds.coherekey}


app:
  # pagination
  pagination:
    write_pages: 5
    page_rows: 4

  # OAuth2
  oauth2:
    password: 1234   # oauth2 인증한 회원에 대한 전용 패스워드, 보안주의!

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: ${rds.kakaoclientid}  # REST Api 앱 키
      redirect-uri: ${rds.kakaoredirecturl} # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token  # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청 URI
